// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFGISXLSQlHyQJBtKUN39_eKD-zPEwZJw',
    appId: '1:477271613298:web:46554412a067ae2a3447eb',
    messagingSenderId: '477271613298',
    projectId: 'chat-app-31c76',
    authDomain: 'chat-app-31c76.firebaseapp.com',
    storageBucket: 'chat-app-31c76.appspot.com',
    measurementId: 'G-0TVRK63XXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj2uiffceq8stBtt5ppe6CGwqDrzEl7SQ',
    appId: '1:477271613298:android:cb175675a22db2e33447eb',
    messagingSenderId: '477271613298',
    projectId: 'chat-app-31c76',
    storageBucket: 'chat-app-31c76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAemeUkRw8d2VvDffcsoS3W6g0tUFgb6fE',
    appId: '1:477271613298:ios:ff4274b2adf690703447eb',
    messagingSenderId: '477271613298',
    projectId: 'chat-app-31c76',
    storageBucket: 'chat-app-31c76.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAemeUkRw8d2VvDffcsoS3W6g0tUFgb6fE',
    appId: '1:477271613298:ios:a922252dc1acff193447eb',
    messagingSenderId: '477271613298',
    projectId: 'chat-app-31c76',
    storageBucket: 'chat-app-31c76.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
